/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:f2f3c5e4-4168-499b-9ed4-865fb2903721",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_4YVxw2Y3T",
    "aws_user_pools_web_client_id": "2ppgph82jlcclcdeelok9lpuiu",
    "oauth": {}
};


export default awsmobile;
